### ISSUE TITLE
If the response is a long text, then only the end of the text is pronounced

### ISSUE THREAD

**Issue by Kochenkov** [just-ai/aimybox-ios-sdk#17]
<img width="393" alt="Снимок экрана 2021-02-09 в 10 33 31" src="https://user-images.githubusercontent.com/38836366/107330646-e9952f00-6ac2-11eb-817d-c884a48f52bb.png">

https://user-images.githubusercontent.com/38836366/107330660-edc14c80-6ac2-11eb-8c13-91b28e4539ba.mp4

**Comment by Ozyrus** [comment]
Баг воспроизводится, когда в ответе ассистента только текст? Если нет, то с какими типами ответа он воспроизводится? Только с этим?

**Comment by Kochenkov** [comment]
да, только текст. Мы используем "type":"text".  Ошибка воспроизводится только тогда, когда текст достаточно длинный. 
Вот еще один пример. Два ответа подряд, и во втором произнесение обрезалось. На андроиде такое не воспроизводится. 

https://user-images.githubusercontent.com/38836366/107343460-624fb780-6ad2-11eb-9485-a8e584ac2b75.mp4



> Баг воспроизводится, когда в ответе ассистента только текст? Если нет, то с какими типами ответа он воспроизводится? Только с этим?

**Comment by Ozyrus** [comment]
Если одно сообщение от ассистента, в котором только текст, баг воспроизводится, или он встречается только в случае, если два сообщения подряд – текст + текст или текст+ виджет/картинка?

**Comment by Kochenkov** [comment]
> Если одно сообщение от ассистента, в котором только текст, баг воспроизводится, или он встречается только в случае, если два сообщения подряд – текст + текст или текст+ виджет/картинка?

если одно сообщение, то тоже воспроизводится

**Comment by Ozyrus** [comment]
@Kochenkov Подскажите, а тут логи не смотрели, возможно тоже дело в том, что текст отрезается?

**Comment by Kochenkov** [comment]
> @Kochenkov Подскажите, а тут логи не смотрели, возможно тоже дело в том, что текст отрезается?

Посмотрели, да, такое же поведение, текст обрезается в tts

**Comment by Ozyrus** [comment]
@Kochenkov в новой версии пофиксили.
