### ISSUE TITLE
the first word is cut off, if not in Russian

### ISSUE THREAD

**Issue by Kochenkov** [just-ai/aimybox-ios-sdk#18]
Такая проблема - при переводе в tts обрезается первое английское слово, остальные слова произносятся нормально.

https://user-images.githubusercontent.com/38836366/107501201-3141b680-6ba8-11eb-90aa-586f185aea7e.mp4

`https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize?folderId=b1gq9gur08br1ugei06g&text=запустит на Гавайях гигантскую виртуальную электростанцию.&lang=ru-RU&voice=kuznetsov&format=lpcm&sampleRateHertz=48000&speed=1.0&emotion=neutral`

**Comment by Ozyrus** [comment]
Вне ассистента запись проигрывается полностью? (Английский голосом поддерживается?)

**Comment by Kochenkov** [comment]
> Вне ассистента запись проигрывается полностью? (Английский голосом поддерживается?)

Не знаю как проиграть запись вне ассистента, но на Андроиде в том же голосе в таком же кейсе, все воспроизводится полностью. 
Плюс к этому, если английское слово стоит в середине запроса, то оно читается нормально на iOS тоже. Пока поймали такую ошибку только в том кейсе, который выше, воспроизводится в 100% случаев.

Наш iOS Разработчик посмотрел логи, и видно, что сдк выполняет такой запрос (первое английское слово в нем отсутствует)
`https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize?folderId=b1gq9gur08br1ugei06g&text=запустит на Гавайях гигантскую виртуальную электростанцию.&lang=ru-RU&voice=kuznetsov&format=lpcm&sampleRateHertz=48000&speed=1.0&emotion=neutral`

**Comment by Ozyrus** [comment]
Ага, спасибо!

**Comment by Ozyrus** [comment]
@Kochenkov в новой версии пофиксили.
