### ISSUE TITLE
Добавить событие для отслеживания метрик Yandex SpeechKit

### ISSUE THREAD

**Issue by GSAleksandrov** [just-ai/aimybox-ios-sdk#23]
Для отслеживания метрик работы голосового помощника необходимо получать информацию о времени обработки запроса TextToSpeech в Yandex SpeechKit Яндекс.Облака. На текущий момент при использовании SDK AimyBox для IOS нет возможности отслеживать данную метрику, есть возможность только получить время запроса с учетом времени, которое еще требуется на произнесение текста.
Необходимо добавить возможность передачи времени ответа или факт получения успешного ответа от Yandex SpeechKit

**Comment by ZharaOo** [comment]
Хотелось бы иметь дополнительные события, чтобы отслеживать начало/окончание запроса в `YandexSynthesisAPI`. Сейчас `speechStarted` срабатывает перед запросом, `speechEnded` после окончания проговаривания. Хотелось бы разделить запрос и проигрывание речи.
В нашем случае это требуется для того, чтобы отслеживать время выполнения запроса в Яндекс.

**Comment by Ozyrus** [comment]
пофиксили в 0.0.11
