### ISSUE TITLE
Добавить возможность воспроизводить звуки начала/окончания слушания.

### ISSUE THREAD

**Issue by ZharaOo** [just-ai/aimybox-ios-sdk#25]
В данный момент в стейтах listening и processing аудио сессия сконфигурирована на запись, поэтому невозможно проиграть звук. Требуется возможность проигрывать звуки при переходе в стейт listening и уходе с него.

**Comment by ErusaevAP** [comment]
Добрый день, не могли бы вы прислать демо-проект где вы пытаетесь реализовать функционал с воспроизведением звука?

**Comment by Ozyrus** [comment]
@ZharaOo привет! можете прислать, плиз? Или сниппет кода, где вы пытаетесь это реализовать

**Comment by ZharaOo** [comment]
Звук проигрывается через AVAudionPlayer, перед этим надо выставить категорию аудио сессии. И на смене AimyboxState в методе в методе `aimybox(_: Aimybox, willMoveFrom oldState: AimyboxState, to newState: AimyboxState)` проигрывать звук. Если `newState == .listening`, то проигрывать звук начала слушания. Если `oldState == .lisntening` , то звук окончания.
То есть проигрывать звук будет как-то так:
```

**Comment by Ozyrus** [comment]
При такой настройке аудиосессии звук проигрывается через верхний динамик, как при разговоре по телефону. Поэтому звук почти не слышно. Нужно придумать альтернативный вариант @ZharaOo @ErusaevAP

**Comment by ErusaevAP** [comment]
Исправлено в `0.0.13`
