### ISSUE TITLE
Неправильное произнесение фразы с ударением

### ISSUE THREAD

**Issue by Kochenkov** [just-ai/aimybox-ios-sdk#26]
**Проблема:** 
Когда на фронт приходит фраза, в которой мы хотим услышать ударение на нужном слове (передаем символ "+"), сдк почему-то обрезает этот символ и фраза произносится некорректно

**Вот пример из логов iOS:** 
`https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize?folderId=b1gq9gur08br1ugei06g&text=Заплат ите 57 407,24 ₽ до 11 марта 2021&lang=ru-RU&speed=1.0&voice=kuznetsov&emotion=neutral&format=lpcm&sampleRateHertz=48000`
хотя приходит фраза: `"tts":"Заплат+ите 57 407,24 ₽ до 11 марта 2021"`

В том же самом кейсе, на андроиде проблема не воспроизводится, и все произносится нормально. Ниже прикрепляю два видео с проблемой на айосе и с нормальным произнесением на андроиде

https://user-images.githubusercontent.com/38836366/110630589-9ba14300-81b6-11eb-88e0-f478a1c8b726.mp4

https://user-images.githubusercontent.com/38836366/110631064-300ba580-81b7-11eb-84f2-ad14ed8daec1.mp4

**Comment by Ozyrus** [comment]
пофиксили в 0.0.11
