### ISSUE TITLE
Проверить блокировку main thread запросом на открытие потока

### ISSUE THREAD

**Issue by Ozyrus** [just-ai/aimybox-ios-sdk#27]
при переходе в стейт listening, каждый раз идет запрос на открытие потока (ConnectivityObserverState: connecting) и похоже, что он блокирует main thread. Плюс имеем задержку на время соединения. Нельзя ли открывать соединение один раз и закрывать его на деинициализации?
![image](https://user-images.githubusercontent.com/12528983/113887055-d6a09180-97c9-11eb-87ee-a9774222103a.png)

**Comment by Erusaev** [comment]
Исправлено в `0.0.13`

**Comment by ErusaevAP** [comment]
Исправлено в `0.0.13`
