### ISSUE TITLE
YandexSpeechToText.stop не успевает закрыть стрим

### ISSUE THREAD

**Issue by ZharaOo** [just-ai/aimybox-ios-sdk#32]
Если вызвать `yandexSpeechToText.stopRecognition` до того, как пришел final result, и сразу же `yandexSpeechToText.startRecognition`, то при открытии новой сессии получаем остаточные результаты от прошлой.

**Шаги:**
1. yandexSpeechToText.startRecognition (либо aimybox.startRecognition)
2. говорим что-нибудь (напр. "привет")
3. получаем partial result `func stt(_ speechToText: SpeechToText, recognitionPartial result: String)`
4. дергаем `yandexSpeechToText.stopRecognition` (либо `aimybox.stopRecognition`, либо `aimybox.sendRequest(query:)`)
5. дергаем `yandexSpeechToText.startRecognition` и ничего не говорим

**Ожидаемое поведение:**
6. Если ничего не говорим, не приходит респонс от `YandexSpeechToText`

**Фактическое поведение:**
6. Если предыдущий стрим не успел закрыться, то получаем `partialResult("привет")` и `finalResult("привет")`

**Comment by ErusaevAP** [comment]
plz test in in 0.0.14
