### ISSUE TITLE
Проблема подключения беспроводных наушников, если находимся на экране голосового помощника Alf.

### ISSUE THREAD

**Issue by maxon2193** [just-ai/aimybox-ios-sdk#34]
Я проверял в наушинках AirPods и Mi True Wireless EBs 
Шаги
1) Авторизоваться в Альфа-мобайл
2) Зайти в голосового помощника 
3) Подключить беспроводные наушники 

Фактический результат:
Блютуз соединение с наушниками установилось, но звук воспроизводится с динамика телефона. Звук появится в наушниках, если выйти из голосового помощника и снова зайти.

Ожидаемый результат
Блютуз соединение с наушниками установилось, звук передается в наушники .

**Comment by dimzfresh** [comment]
Исправлено в версии 0.0.22
