### ISSUE TITLE
Демо-апп крашится при работе с беспроводными наушниками. 

### ISSUE THREAD

**Issue by maxon2193** [just-ai/aimybox-ios-sdk#41]
Посмотрел демоапп с конфигами альфа-мобайла. Я смотрел на iPhone 11 iOS 15.1. Проверял на AirPods и сторонних беспроводных наушниках (MI True Wireless EBs и JBL FREE).

Я распишу 4 кейса , которые могут привести к крашу. Ожидаемый результат для этих кейсов : Приложение не должно крашится.

Кейс 1

1. Зайти в приложение с подключенными наушниками.
2. Включаем микрофон , нажав на соответствующую иконку
3. Выключаем микрофон, нажав на эту же иконку
4. Подключаем беспроводные наушники.
5. Наушники подключены. Снова включаем микрофон.

Фактический результат: Произойдёт краш приложения

Кейс 2

1. Зайти в приложение с подключенными наушниками
2. Включаем микрофон, нажав на соответствующую иконку
3. Выключаем микрофон, нажав на эту же иконку
4. Отключаем беспроводные наушники.
5. Наушники отключены. Снова включаем микрофон.

Фактический результат: Произойдёт краш приложения

Кейс 3

1. Зайти в приложение без подключенных наушников
2. Включаем микрофон , нажав на соответствующую иконку
3. Выключаем микрофон, нажав на эту же иконку
4. Подключаем беспроводные наушники.
5. Наушники подключены. Пишем текст голосовому помощнику или выбираем быструю команду.
6. Голосовой помощник ответил голосом .

Фактический результат: После того как он закончит речь, то приложение крашится.

Кейс 4

1. Зайти в приложение с подключенными наушниками
2. Включаем микрофон , нажав на соответствующую иконку
3. Выключаем микрофон, нажав на эту же иконку
4. Отключаем беспроводные наушники.
5. Наушники отключены. Пишем текст голосовому помощнику или выбираем быструю команду.
6. Голосовой помощник ответил голосом .

Фактический результат: После того как он закончит речь, то приложение крашится.

**Comment by dimzfresh** [comment]
Исправлено в версии 0.0.22
