### ISSUE TITLE
В демо-аппе при подключенных наушниках не работает распознавание голоса через микрофон и слышу гудки при включении/выключения микрофона на наушниках.

### ISSUE THREAD

**Issue by maxon2193** [just-ai/aimybox-ios-sdk#42]
Посмотрел демоапп с конфигами альфа-мобайла. Я смотрел на iPhone 11 iOS 15.1. Проверял на AirPods и сторонних беспроводных наушниках (MI True Wireless EBs и JBL FREE).

**Баг №1. В сторонних наушниках (не в AirPods) слышу гудки при включении/выключения микрофона.**

Кейс 1
1. Зайти в приложение с подключенными наушниками.
2. Пишем текст голосовому помощнику или выбираем быструю команду.
3. Слушаем ответ голосового помощника

Кейс 2
1. Зайти в приложение с подключенными наушниками.
2. Включаем микрофон, нажав на соответствующую иконку 

Фактический результат: Перед тем как голосовой помощник начнет говорить и после того как закончит, я слышу гудки в наушниках из-за того, что в них включается и включается микрофон. При включении микрофона, нажав на соответствующую иконку, тоже слышу гудки.  На эйрподсах такие звуки не воспроизводятся. Только в сторонних наушниках . 
**Ожидаемый результат распишу ниже, после 2 бага.**

**Баг №2. При подключенных наушниках не работает распознавание голоса через микрофон**

1. Зайти в приложение, уже подключив наушники 
2. Включаем микрофон , нажав на соответствующую иконку 
3. Что-нибудь говорим в микрофон
Фактический результат: Голос не распознается в микрофон. Такая проблема для всех беспроводных наушников. 

**Ожидаемый результат для багов №1 и №2**
**_Для наушников AirPods:_** Микрофон должен работать на наушниках.
**_Для сторонних наушников:_** Так как в них слышим гудки при включении/отключении микрофона(напомню что в эйрподсах нету таких звуков), то микрофон в наушниках не должен работать и распознавание голоса должно происходить через микрофон телефона. 
P.S. Я решил посмотреть как работает Сири через наушники. Если с ней общаемся через эйрподсы, то микрофон будет работать на наушниках . А если с ней пообщаться через сторонние наушники, то микрофон будет работать в телефоне.

**Comment by dimzfresh** [comment]
Исправлено в версии 0.0.22
