### ISSUE TITLE
В демо-аппе в беспроводных наушниках воспроизводится сжатый звук голосового помощника

### ISSUE THREAD

**Issue by maxon2193** [just-ai/aimybox-ios-sdk#43]
Посмотрел демоапп с конфигами альфа-мобайла. Я смотрел на iPhone 11 iOS 15.1. Проверял на AirPods и сторонних беспроводных наушниках (MI True Wireless EBs и JBL FREE).

1. Зайти в приложение, уже подключив наушники.
2. Пишем текст голосовому помощнику или выбираем быструю команду.
3. Слушаем ответ голосового помощника.
Фактический результат: Я слышу сжатый звук голосового помощника 
Ожидаемый результат: Звук не должен быть сжатым.

**Comment by dimzfresh** [comment]
Исправлено в версии 0.0.22
